#ifndef IMAGEPROCESSOR_GLOBAL_H
#define IMAGEPROCESSOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IMAGEPROCESSOR_LIBRARY)
#  define IMAGEPROCESSORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define IMAGEPROCESSORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // IMAGEPROCESSOR_GLOBAL_H
